// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEPHF5d1geT46d77p7mT1LY-Qtg6UvAVU',
    appId: '1:1090035939317:web:bf9b3f2a980f3e8f78d2bc',
    messagingSenderId: '1090035939317',
    projectId: 'entrepreneur-survey',
    authDomain: 'entrepreneur-survey.firebaseapp.com',
    storageBucket: 'entrepreneur-survey.appspot.com',
    measurementId: 'G-NFS67WZNPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiP13ImuxCG9AxL8o4Ml7f-y3I-r50bgQ',
    appId: '1:1090035939317:android:4f820dfe8a3b446b78d2bc',
    messagingSenderId: '1090035939317',
    projectId: 'entrepreneur-survey',
    storageBucket: 'entrepreneur-survey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBveJ6DCZ8zL8jTblCdVnL0URkPoKtqsRg',
    appId: '1:1090035939317:ios:5cbb5e3b71569f7e78d2bc',
    messagingSenderId: '1090035939317',
    projectId: 'entrepreneur-survey',
    storageBucket: 'entrepreneur-survey.appspot.com',
    iosBundleId: 'com.example.hack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBveJ6DCZ8zL8jTblCdVnL0URkPoKtqsRg',
    appId: '1:1090035939317:ios:4552e35b8481aff478d2bc',
    messagingSenderId: '1090035939317',
    projectId: 'entrepreneur-survey',
    storageBucket: 'entrepreneur-survey.appspot.com',
    iosBundleId: 'com.example.hack.RunnerTests',
  );
}
